version: 2

jobs:
  build:
    working_directory: ~/crowdsorter

    docker:
      - image: python:3.6.7
        environment:
          RANDOM_SEED: 0
      - image: mongo:3.4.4

    steps:
      - checkout

      - run:
          name: Installing System Dependencies
          command: pip install pipenv

      - run:
          name: Checking System Dependencies
          command: make doctor

      - type: cache-restore
        key: pipenv-{{ checksum "Pipfile.lock" }}

      - run:
          name: Installing Project Dependencies
          command: make install

      - type: cache-save
        key: pipenv-{{ checksum "Pipfile.lock" }}
        paths:
          - .venv

      - run:
          name: Checking Code
          command: make check

      - run:
          name: Running Tests
          command: make test

