version: 2

executorType: docker

containerInfo:
  - image: python:3.6.0rc2
  - image: mongo:3.2.11

stages:
  build:
    workDir: /home/ubuntu/crowdsorter
    steps:
      - type: checkout
      - type: shell
        command: make doctor
      - type: shell
        command: make install
      - type: shell
        command: make check
      - type: shell
        command: make test
        # TODO: get reports working with CircleCI 2.0
