site_name: crowdsorter
site_description: Crowdsourced list sorting.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/crowdsorter

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
